inherit_gem:
  rubocop-inst:
    - rubocop.yml

require:
  - rubocop-rspec

plugins:
  - rubocop-rails
  - rubocop-factory_bot

AllCops:
  TargetRubyVersion: 3.2.0
  SuggestExtensions: false
  Exclude:
   - inst-jobs_statsd.gemspec
Naming/FileName:
  Exclude:
   - lib/inst-jobs-statsd.rb

Layout/LineLength:
  Exclude:
    - 'spec/**/*'

Rails/SkipsModelValidations:
  Enabled: false

RSpec/AnyInstance:
  Enabled: false
RSpec/InstanceVariable:
  Enabled: false
RSpec/VerifiedDoubles:
  Enabled: false

Style/Documentation:
  Enabled: false
Style/FetchEnvVar:
  Enabled: false
#Ignore some cops that are not relevant for the upgrade but should be looked at
Gemspec/DevelopmentDependencies:
  Enabled: false
RSpec/MultipleExpectations:
  Enabled: false
RSpec/ExampleLength:
  Enabled: false
RSpec/NestedGroups:
  Enabled: false
RSpec/MessageSpies:
  Enabled: false

# Explicitly disable the problematic Capybara cop causing crashes
Capybara/RSpec/PredicateMatcher:
  Enabled: false
