inherit_gem:
  rubocop-inst:
  - rubocop.yml
  - rubocop-rspec.yml

require:
 - rubocop-factory_bot
 - rubocop-rake
 - rubocop-rails

AllCops:
  TargetRubyVersion: 2.7

Naming/FileName:
  Exclude:
   - lib/inst-jobs-statsd.rb

Layout/LineLength:
  Exclude:
    - 'spec/**/*'

Rails/SkipsModelValidations:
  Enabled: false

RSpec/AnyInstance:
  Enabled: false
RSpec/InstanceVariable:
  Enabled: false
RSpec/VerifiedDoubles:
  Enabled: false

Style/Documentation:
  Enabled: false
Style/FetchEnvVar:
  Enabled: false
