version: '2'

services:
  app:
    build: .
    platform: linux/amd64
    environment:
      INST_STATSD_HOST: graphite
      INST_STATSD_PORT: "8125"
      INST_STATSD_NAMESPACE: inst-jobs-statsd
      INST_STATSD_APPEND_HOSTNAME: "false"
      RAILS_ENV: test
      TEST_DB_HOST: postgres
      TEST_DB_USERNAME: postgres
      TEST_ENV_NUMBER: "1"
    links:
      - postgres
      - graphite

  postgres:
    image: postgres:9.6
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust

  graphite:
    image: hopsoft/graphite-statsd
